import Head from "next/head";
import Experience from "../Components/Experience";
import Footer from "../Components/Footer";
import NavBar from "../Components/NavBar";
function experience() {
  return (
    <>
      <Head>
        <title>Abir Santra | About page </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./assets/favicone.png" />
      </Head>
      <div className="flex flex-col  w-full h-full">
        <main className="w-screen h-full flex flex-col gap-y-4">
          <NavBar />
          <div className="mt-20">
            <div className="flex justify-center items-center">
              <h2 className="text-green-500 font-extrabold text-3xl capitalize">
                experience
              </h2>
            </div>
            <Experience />
          </div>
        </main>
        <Footer />
      </div>
    </>
  );
}

export default experience;
